### ISSUE TITLE
Error Crawlee + Cheerio Apify Typescript template

### ISSUE THREAD

**Issue by LouisDeconinck** [apify/apify-cli#673]
Using the apify create command and selecting Typescript > Crawlee + Cheerio gets me the following error.

```
PS C:\Users\name\Documents\apify> apify create
? Name of your new Actor: test4
? Choose the programming language of your new Actor: TypeScript
? Choose a template for your new Actor. Detailed information about the template will be shown in the next step. Crawlee + Cheerio 
? Do you want to install the following template?
 Crawlee + Cheerio:
 A scraper example that uses Cheerio to parse HTML. It's fast, but it can't run the website's JavaScript or pass JS anti-scraping 
challenges. Install template
Run: npm.cmd install --omit=optional
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\name\\Documents\\apify\\test4\\node_modules',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\name\Documents\apify\test4\node_modules\eslint-plugin-react'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\name\\Documents\\apify\\test4\\node_modules\\eslint-plugin-react'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\name\Documents\apify\test4\node_modules\esbuild
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm error C:\Users\name\Documents\apify\test4\node_modules\esbuild\install.js:134
npm error     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm error           ^
npm error
npm error Error: Expected "0.23.1" but got "0.21.5"
npm error     at validateBinaryVersion (C:\Users\name\Documents\apify\test4\node_modules\esbuild\install.js:134:11)
npm error     at C:\Users\name\Documents\apify\test4\node_modules\esbuild\install.js:282:5
npm error
npm error Node.js v20.17.0
npm error A complete log of this run can be found in: C:\Users\name\AppData\Local\npm-cache\_logs\2024-10-01T19_21_37_128Z-debug-0.log
    Error: npm.cmd exited with code 1
```

If I afterwards try to use apify run I get: 
```
Error: Actor is of an unknown format. Make sure either the 'package.json' file or 'src/__main__.py' file exists or you are in a migrated Scrapy project.
```

Crawlee version: 3.5.4
Node version: 20.17
Operating system: Windows

**Comment by LouisDeconinck** [comment]
Tried again today without making any changes and worked without any issues. So, perhaps this is solved? No idea why I got the error in the first place.

**Comment by B4nan** [comment]
Please don't open multiple issues about the same. Closing this one since it has nothing to do with the CLI.
